<?php return array (
  'AutovmDefaultCurrencyID' => '1',
  'AutovmDefaultCurrencySymbol' => '$',
  'PlaceCurrencySymbol' => 'option2',
  'ShowExchange' => 'option1',
  'ChargeModuleEnable' => 'option1',
  'ConsoleRoute' => 'https://www.mywhmcs.com/console',
  'TopupLink' => '/clientarea.php?action=addfunds',
  'minimumChargeInAutovmCurrency' => '3',
  'DefaultMonthlyDecimal' => 'option1',
  'DefaultHourlyDecimal' => 'option3',
  'DefaultBalanceDecimalWhmcs' => 'option1',
  'DefaultBalanceDecimalCloud' => 'option1',
  'DefaultChargeAmountDecimalWhmcs' => 'option1',
  'DefaultChargeAmountDecimalCloud' => 'option1',
  'DefaultCreditDecimalWhmcs' => 'option1',
  'DefaultCreditDecimalCloud' => 'option1',
  'DefaultMinimumDecimalWhmcs' => 'option1',
  'DefaultMinimumDecimalCloud' => 'option1',
  'DefaultRatioDecimal' => 'option2',
);